[2024-07-13T18:45:53.744+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_cards.create_table manual__2024-07-13T13:15:51.455208+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
