[2024-07-16T05:26:59.336+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T05:26:59.368+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_load_credit_scores.insert_table manual__2024-07-15T23:56:32.024246+00:00 [queued]>
[2024-07-16T05:26:59.381+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_load_credit_scores.insert_table manual__2024-07-15T23:56:32.024246+00:00 [queued]>
[2024-07-16T05:26:59.382+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-16T05:26:59.400+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_table> on 2024-07-15 23:56:32.024246+00:00
[2024-07-16T05:26:59.405+0530] {standard_task_runner.py:63} INFO - Started process 20522 to run task
[2024-07-16T05:26:59.411+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_load_credit_scores', 'insert_table', 'manual__2024-07-15T23:56:32.024246+00:00', '--job-id', '1421', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_credit_scores.py', '--cfg-path', '/tmp/tmp7mxik4o8']
[2024-07-16T05:26:59.414+0530] {standard_task_runner.py:91} INFO - Job 1421: Subtask insert_table
[2024-07-16T05:26:59.460+0530] {task_command.py:426} INFO - Running <TaskInstance: raw_load_credit_scores.insert_table manual__2024-07-15T23:56:32.024246+00:00 [running]> on host kali
[2024-07-16T05:26:59.548+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_load_credit_scores' AIRFLOW_CTX_TASK_ID='insert_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T23:56:32.024246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T23:56:32.024246+00:00'
[2024-07-16T05:26:59.549+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T05:26:59.577+0530] {logging_mixin.py:188} INFO - customer_id`,`credit_score`,`score_date`,`ingetion_timestamp
[2024-07-16T05:26:59.582+0530] {logging_mixin.py:188} INFO - ('f151fd94-4892-4ddc-b8b6-7b97e97a05db', 471, '2024-07-14', Timestamp('2024-07-16 05:26:59.575343'))
[2024-07-16T05:26:59.583+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T05:26:59.583+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_credit_scores.py", line 52, in insert_table
    load_csv_to_mysql(csv_file, table_name)
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_credit_scores.py", line 46, in load_csv_to_mysql
    cursor.execute(sql, tuple(row))
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'credit_score' in 'field list'")
[2024-07-16T05:26:59.592+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=raw_load_credit_scores, task_id=insert_table, run_id=manual__2024-07-15T23:56:32.024246+00:00, execution_date=20240715T235632, start_date=20240715T235659, end_date=20240715T235659
[2024-07-16T05:26:59.603+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1421 for task insert_table ((1054, "Unknown column 'credit_score' in 'field list'"); 20522)
[2024-07-16T05:26:59.624+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T05:26:59.647+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T05:26:59.648+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
