[2024-07-12T01:47:49.244+0530] {processor.py:161} INFO - Started process (PID=36644) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:47:49.245+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:47:49.247+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:47:49.246+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:47:49.266+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:47:49.265+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from scripts.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:47:49.266+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:47:49.289+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.051 seconds
[2024-07-12T01:48:19.522+0530] {processor.py:161} INFO - Started process (PID=37120) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:19.523+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:48:19.525+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:19.525+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:19.544+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:19.543+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from scripts.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:48:19.545+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:19.562+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.047 seconds
[2024-07-12T01:48:51.082+0530] {processor.py:161} INFO - Started process (PID=37503) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:51.083+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:48:51.085+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:51.085+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:51.100+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:51.099+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from scripts.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:48:51.101+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:51.125+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.048 seconds
[2024-07-12T01:48:55.901+0530] {processor.py:161} INFO - Started process (PID=37566) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:55.902+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:48:55.904+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:55.903+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:55.924+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:55.923+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:48:55.925+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:48:55.954+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.061 seconds
[2024-07-12T01:49:26.368+0530] {processor.py:161} INFO - Started process (PID=38017) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:26.369+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:49:26.371+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:26.370+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:26.389+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:26.388+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:49:26.390+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:26.408+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.046 seconds
[2024-07-12T01:49:57.247+0530] {processor.py:161} INFO - Started process (PID=38337) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:57.248+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:49:57.249+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:57.249+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:57.266+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:57.265+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:49:57.266+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:49:57.283+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.042 seconds
[2024-07-12T01:50:27.979+0530] {processor.py:161} INFO - Started process (PID=38762) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:27.980+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:50:27.982+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:27.982+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:28.003+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:28.002+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_insurance.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:50:28.003+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:28.021+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.050 seconds
[2024-07-12T01:50:58.196+0530] {processor.py:161} INFO - Started process (PID=39186) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:58.197+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:50:58.199+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:58.198+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:58.219+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:58.218+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_insurance.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:50:58.220+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:50:58.239+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.051 seconds
[2024-07-12T01:51:28.291+0530] {processor.py:161} INFO - Started process (PID=39593) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:51:28.291+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:51:28.294+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:51:28.294+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:51:28.312+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:51:28.311+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py", line 13, in <module>
    from models.raw_models.raw_load_insurance import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_insurance.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:51:28.313+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:51:28.331+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.047 seconds
[2024-07-12T01:52:03.301+0530] {processor.py:161} INFO - Started process (PID=40301) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:52:03.303+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py for tasks to queue
[2024-07-12T01:52:03.305+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.305+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:52:03.783+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.783+0530] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-12T01:52:03.789+0530] {processor.py:840} INFO - DAG(s) 'raw_load_insurance' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py
[2024-07-12T01:52:03.907+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.906+0530] {override.py:1847} INFO - Created Permission View: can delete on DAG:raw_load_insurance
[2024-07-12T01:52:03.934+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.934+0530] {override.py:1847} INFO - Created Permission View: can read on DAG:raw_load_insurance
[2024-07-12T01:52:03.943+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.942+0530] {override.py:1847} INFO - Created Permission View: can edit on DAG:raw_load_insurance
[2024-07-12T01:52:03.944+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.943+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T01:52:03.958+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.957+0530] {dag.py:3118} INFO - Creating ORM DAG for raw_load_insurance
[2024-07-12T01:52:03.959+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.958+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_insurance to None, run_after=None
[2024-07-12T01:52:03.984+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_insurance.py took 0.692 seconds
