[2024-07-13T17:11:10.961+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T17:11:10.991+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_load_atms.insert_table manual__2024-07-13T11:41:03.869983+00:00 [queued]>
[2024-07-13T17:11:11.001+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_load_atms.insert_table manual__2024-07-13T11:41:03.869983+00:00 [queued]>
[2024-07-13T17:11:11.001+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-13T17:11:11.018+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_table> on 2024-07-13 11:41:03.869983+00:00
[2024-07-13T17:11:11.026+0530] {standard_task_runner.py:63} INFO - Started process 72554 to run task
[2024-07-13T17:11:11.030+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_load_atms', 'insert_table', 'manual__2024-07-13T11:41:03.869983+00:00', '--job-id', '1251', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_atms.py', '--cfg-path', '/tmp/tmppa5be5hl']
[2024-07-13T17:11:11.031+0530] {standard_task_runner.py:91} INFO - Job 1251: Subtask insert_table
[2024-07-13T17:11:11.081+0530] {task_command.py:426} INFO - Running <TaskInstance: raw_load_atms.insert_table manual__2024-07-13T11:41:03.869983+00:00 [running]> on host kali
[2024-07-13T17:11:11.162+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_load_atms' AIRFLOW_CTX_TASK_ID='insert_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T11:41:03.869983+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T11:41:03.869983+00:00'
[2024-07-13T17:11:11.164+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T17:11:11.177+0530] {logging_mixin.py:188} INFO - atm_id`,`branch_id`,`location`,`status`,`installation_date`,`ingetion_timestamp
[2024-07-13T17:11:11.178+0530] {logging_mixin.py:188} INFO - ('70d8a24b-e26b-43c4-afd9-fa1185b9039d', 'dab54483-7041-4d76-ac95-934241f3d49f', '65982 Patrick Walks Suite 305\nBrandonville, UT 76225', 'out of service', '2024-07-09', Timestamp('2024-07-13 17:11:11.174550'))
[2024-07-13T17:11:11.179+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T17:11:11.179+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_atms.py", line 51, in insert_table
    load_csv_to_mysql(csv_file, table_name)
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_atms.py", line 45, in load_csv_to_mysql
    cursor.execute(sql, tuple(row))
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'ingetion_timestamp' in 'field list'")
[2024-07-13T17:11:11.186+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=raw_load_atms, task_id=insert_table, run_id=manual__2024-07-13T11:41:03.869983+00:00, execution_date=20240713T114103, start_date=20240713T114110, end_date=20240713T114111
[2024-07-13T17:11:11.199+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1251 for task insert_table ((1054, "Unknown column 'ingetion_timestamp' in 'field list'"); 72554)
[2024-07-13T17:11:11.243+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T17:11:11.290+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T17:11:11.292+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
