[2024-07-13T18:23:40.395+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T18:23:40.426+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_load_atms.insert_table manual__2024-07-13T12:53:13.218502+00:00 [queued]>
[2024-07-13T18:23:40.436+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_load_atms.insert_table manual__2024-07-13T12:53:13.218502+00:00 [queued]>
[2024-07-13T18:23:40.437+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-13T18:23:40.454+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_table> on 2024-07-13 12:53:13.218502+00:00
[2024-07-13T18:23:40.460+0530] {standard_task_runner.py:63} INFO - Started process 11298 to run task
[2024-07-13T18:23:40.464+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_load_atms', 'insert_table', 'manual__2024-07-13T12:53:13.218502+00:00', '--job-id', '1263', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_atms.py', '--cfg-path', '/tmp/tmpj4ebktmq']
[2024-07-13T18:23:40.465+0530] {standard_task_runner.py:91} INFO - Job 1263: Subtask insert_table
[2024-07-13T18:23:40.512+0530] {task_command.py:426} INFO - Running <TaskInstance: raw_load_atms.insert_table manual__2024-07-13T12:53:13.218502+00:00 [running]> on host kali
[2024-07-13T18:23:40.593+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_load_atms' AIRFLOW_CTX_TASK_ID='insert_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T12:53:13.218502+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T12:53:13.218502+00:00'
[2024-07-13T18:23:40.594+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T18:23:40.605+0530] {logging_mixin.py:188} INFO - atm_id`,`branch_id`,`location`,`status`,`installation_date`,`ingetion_timestamp
[2024-07-13T18:23:40.607+0530] {logging_mixin.py:188} INFO - ('70d8a24b-e26b-43c4-afd9-fa1185b9039d', 'dab54483-7041-4d76-ac95-934241f3d49f', '65982 Patrick Walks Suite 305\nBrandonville, UT 76225', 'out of service', '2024-07-09', Timestamp('2024-07-13 18:23:40.601584'))
[2024-07-13T18:23:40.608+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T18:23:40.609+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_atms.py", line 52, in insert_table
    load_csv_to_mysql(csv_file, table_name)
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_atms.py", line 46, in load_csv_to_mysql
    cursor.execute(sql, tuple(row))
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'ingetion_timestamp' in 'field list'")
[2024-07-13T18:23:40.616+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=raw_load_atms, task_id=insert_table, run_id=manual__2024-07-13T12:53:13.218502+00:00, execution_date=20240713T125313, start_date=20240713T125340, end_date=20240713T125340
[2024-07-13T18:23:40.630+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1263 for task insert_table ((1054, "Unknown column 'ingetion_timestamp' in 'field list'"); 11298)
[2024-07-13T18:23:40.677+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T18:23:40.718+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T18:23:40.721+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
