[2024-07-16T05:26:35.165+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_credit_scores.create_table manual__2024-07-15T23:56:32.024246+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
