[2024-07-13T18:46:50.661+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_insurance.tuncate_table manual__2024-07-13T13:16:42.801579+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
