[2024-07-13T18:24:55.916+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_atms.create_table manual__2024-07-13T12:53:13.218502+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
