[2024-07-13T18:50:16.664+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T18:50:16.814+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_load_investments.insert_table manual__2024-07-13T13:18:04.951746+00:00 [queued]>
[2024-07-13T18:50:16.830+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_load_investments.insert_table manual__2024-07-13T13:18:04.951746+00:00 [queued]>
[2024-07-13T18:50:16.830+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-13T18:50:16.851+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_table> on 2024-07-13 13:18:04.951746+00:00
[2024-07-13T18:50:16.860+0530] {standard_task_runner.py:63} INFO - Started process 48527 to run task
[2024-07-13T18:50:16.864+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_load_investments', 'insert_table', 'manual__2024-07-13T13:18:04.951746+00:00', '--job-id', '1322', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_investments.py', '--cfg-path', '/tmp/tmp6p6hc6u6']
[2024-07-13T18:50:16.867+0530] {standard_task_runner.py:91} INFO - Job 1322: Subtask insert_table
[2024-07-13T18:50:16.957+0530] {task_command.py:426} INFO - Running <TaskInstance: raw_load_investments.insert_table manual__2024-07-13T13:18:04.951746+00:00 [running]> on host kali
[2024-07-13T18:50:17.107+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_load_investments' AIRFLOW_CTX_TASK_ID='insert_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T13:18:04.951746+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T13:18:04.951746+00:00'
[2024-07-13T18:50:17.108+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T18:50:17.136+0530] {logging_mixin.py:188} INFO - investment_id`,`customer_id`,`investment_type`,`amount`,`start_date`,`end_date`,`ingetion_timestamp
[2024-07-13T18:50:17.137+0530] {logging_mixin.py:188} INFO - ('6792789a-91dc-40ea-acc0-ed21ed4287cd', '94ab592b-cada-450b-b970-97ef5b31011d', 'stocks', 75522.57, '2024-07-09', '2025-05-31', Timestamp('2024-07-13 18:50:17.134432'))
[2024-07-13T18:50:17.140+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T18:50:17.140+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_investments.py", line 55, in insert_table
    load_csv_to_mysql(csv_file, table_name)
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_investments.py", line 49, in load_csv_to_mysql
    cursor.execute(sql, tuple(row))
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'investment_type' in 'field list'")
[2024-07-13T18:50:17.149+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=raw_load_investments, task_id=insert_table, run_id=manual__2024-07-13T13:18:04.951746+00:00, execution_date=20240713T131804, start_date=20240713T132016, end_date=20240713T132017
[2024-07-13T18:50:17.165+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1322 for task insert_table ((1054, "Unknown column 'investment_type' in 'field list'"); 48527)
[2024-07-13T18:50:17.205+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T18:50:17.229+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T18:50:17.230+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
